FROM apache/airflow

ARG LIMINAL_VERSION='apache-liminal'
ARG DAG_FOLDER='/opt/airflow/dags/'
ADD scripts/* ${DAG_FOLDER}
ADD liminal/runners/airflow/dag/liminal_dags.py ${DAG_FOLDER}

USER root

RUN apt-get update && apt-get install -y --no-install-recommends git

USER airflow

RUN pip --disable-pip-version-check install -r /opt/airflow/dags/requirements-airflow.txt --user
RUN pip --disable-pip-version-check install --user --no-deps ${LIMINAL_VERSION}


